steps:
  - trigger: agent-builder
    async: false
    build:
      env:
        QUEUE_NAME="${BUILDKITE_PIPELINE_SLUG}"
    
  - command: echo "I am $BUIDLKITE_AGENT_NAME"
    agents:
      queue: ${BUILDKITE_PIPELINE_SLUG}-agent
